name: Test

# Workflow conditions
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  release:
    types: [published]

# env:
#   GITHUB_USERNAME: ${{ github.actor }}
#   GITHUB_TOKEN: ${{ github.token }}
#   DOCKER_IMAGE: "ghcr.io/${{ github.repository }}"

jobs:

  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          # linux
          - os: ubuntu-latest
            arch: linux
          # windows
          - os: windows-latest
            arch: windows
          # # macOS
          # - os: macos-latest
          #   arch: macos
          # # docker
          # - os: ubuntu-latest
          #   arch: docker
        python-version: ["3.10"]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install
        if: ${{ matrix.arch != 'docker' }}
        run: |
          python -m pip install --upgrade pip
          pip install -e .[test]

      - name: Pytest
        run: |
          pytest -v

      - name: CLI Help
        run: |
          pangonet --help

      - name: CLI Run
        run: |     
          pangonet --output-prefix pango --output-all
