name: Test

# Workflow conditions
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  release:
    types: [published]

env:
  GITHUB_USERNAME: ${{ github.actor }}
  GITHUB_TOKEN: ${{ github.token }}
  DOCKER_IMAGE: "ghcr.io/${{ github.repository }}"

jobs:

  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10"]
        include:
          - os: ubuntu-latest
            arch: linux
          # - os: ubuntu-latest
          #   arch: docker
          - os: windows-latest
            arch: windows
          - os: macos-latest
            arch: macos

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        if: ${{ matrix.arch != 'docker' }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install
        if: ${{ matrix.arch != 'docker' }}
        run: |
          python -m pip install --upgrade pip
          pip install -e .[test]

      - name: Pytest
        run: |
          pytest -v

      - name: CLI Help
        run: |
          pangonet --help

      - name: CLI Run
        run: |     
          pangonet --output-prefix output/pango --output-all
